name: Run Scoring-STOXX daily

on:
  schedule:
    - cron: "30 6 * * *"   # tous les jours à 06:30 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    env:
      TZ: Europe/Paris
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"           # optionnel: accélère les installs

      - name: Install LP solver (PuLP)
        run: |
          sudo apt-get update
          sudo apt-get install -y coinor-cbc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python Scoring-STOXX.py

      - name: Upload outputs (optionnel)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ github.run_id }}
          path: |
            **/*.xlsx
