name: Run Scoring-STOXX daily

on:
  schedule:
    # ⏰ Tous les jours à 06:30 UTC (07:30/08:30 à Paris selon saison)
    - cron: "30 6 * * *"
  workflow_dispatch: {}   # Lancer manuellement depuis l’onglet Actions

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    # ⚠️ Les secrets que tu as créés seront injectés ici
    env:
      TZ: Europe/Paris
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install LP solver (PuLP)
        run: |
          sudo apt-get update
          sudo apt-get install -y coinor-cbc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python Scoring-STOXX.py

      # (Optionnel) Récupérer les fichiers Excel générés depuis l’onglet Actions
      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ github.run_id }}
          path: |
            **/*.xlsx
